# Generated by Django 2.2.4 on 2020-03-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200310_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_question',
            name='option4',
            field=models.CharField(max_length=255, verbose_name='Option4'),
        ),
        migrations.CreateModel(
            name='Answer_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rand_num', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=255, verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Quiz_Question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StudentDetail')),
            ],
        ),
    ]
