# Generated by Django 2.2.4 on 2020-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200327_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_detail',
            name='question',
            field=models.IntegerField(null=True),
        ),
    ]
