# Generated by Django 2.2.4 on 2020-03-31 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200330_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_detail',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Question_Category'),
        ),
    ]
