# Generated by Django 3.2 on 2024-02-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_answer_detail_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Question')),
                ('content', models.TextField(max_length=3000, verbose_name='Content')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question_category')),
            ],
        ),
    ]
